name: Deploy Actions

on:
  push:
    paths:
      - .github/workflows/deploy-actions.yaml
      - actions/**
    branches:
      - main

jobs:
  deploy:
    name: Deploy Actions
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['18']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.1.0
        with:
          os: ${{ matrix.os }}
          version: 9.3.0
      - name: Deploy
        env:
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE}}
          AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
        uses: adobe/aio-apps-action@2.0.2
        with:
          os: ${{ matrix.os }}
          command: deploy
          working-directory: actions/mdconverter.action