name: Deploy Actions

on:
  push:
    paths:
      - .github/workflows/deploy-actions.yaml
      - actions/**
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: exlm
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install -g @adobe/aio-cli
    - name: Run npm ci (mdconverter)
      run: npm ci
      working-directory: actions/mdconverter.action
    - run: aio app deploy
      working-directory: actions
      env:
        AIO_runtime_auth: ${{ secrets.AIO_runtime_auth }}
        AIO_runtime_namespace: ${{ secrets.AIO_runtime_auth }}
