name: Deploy Actions

on:
  push:
    paths:
      - .github/workflows/deploy-actions.yaml
      - actions/**
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: exlm
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm install -g @adobe/aio-cli
    - name: Run npm ci (actions)
      run: npm ci
      working-directory: actions
    - name: Run npm ci (mdconverter)
      run: npm ci
      working-directory: actions/mdconverter.action
    - name: Deploy (mdconverter)
      run: ./node_modules/.bin/aio app deploy
      working-directory: actions
      env:
        AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
        AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
